### PR TITLE
Classifier validation fixes

### PR DESCRIPTION
**Pull request by DavidStirling**
Turns out that if someone trains their classifier with a combined object table, the target object isn't always the one we want a measurement for. To address this I've revised the validation function to properly check the source object for each measurement. This previously wasn't the case because the `Rules` class from FGB doesn't supply object names, so I've reworked that so that we fetch the object names when loading the rules file.

I've also made some tweaks to generate a better colour map for the figure display.

Still need to apply this to FilterObjects, so this is a WIP for now.

### CODE REVIEW

**Comment by DavidStirling** [comment]
Applied this to FilterObjects too

**Comment by bethac07** [comment]
Do we have a handy test set for this?

**Comment by DavidStirling** [comment]
Maybe try this

[ClassifierTest.zip](https://github.com/CellProfiler/CellProfiler/files/6818457/ClassifierTest.zip)

**Comment by bethac07** [comment]
```
Failed to run module ClassifyObjects
Traceback (most recent call last):
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 3370, in do_step
    module.display(workspace_model, fig)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/classifyobjects.py", line 972, in display
    self.display_classifier_model(workspace, figure)
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/modules/classifyobjects.py", line 1367, in display_classifier_model
    cmap = figure.return_cmap()
  File "/Users/bcimini/Documents/GitHub/CellProfiler/CellProfiler/cellprofiler/gui/figure/_figure.py", line 1882, in return_cmap
    colormap = matplotlib.cm.get_cmap(get_default_colormap(), lut=nindexes,).copy()
AttributeError: 'LinearSegmentedColormap' object has no attribute 'copy'
```
```
bcimini$ pip freeze | grep mat
matplotlib==3.1.3
```

**Comment by bethac07** [comment]
If I revert the change in _figure, everything LGTM.  LMK how you want to proceed with respect to that change.

**Comment by bethac07** [comment]
Nevermind, just kidding, a bunch of test failures in filter_objects now, sorry 🙃

**Comment by DavidStirling** [comment]
I'll get right on it. For MPL we can just revert, I forgot we were pinned to 3.1 and that was only to fix a deprecation warning.

**Comment by DavidStirling** [comment]
_Of course_ the tests generate a nonsensical object name and assume the filter won't care

**Pull request merged**
