### PR TITLE
64-bit on OS X

### PR DESCRIPTION
**Pull request by 0x00B1**

### CODE REVIEW

**Comment by 0x00B1** [comment]
@LeeKamentsky Would you mind testing on Windows?

**Comment by LeeKamentsky** [comment]
Doing so right now. WX 2.8 has some minor breakage, so I will submit a patch that should work on both 2.8 and 3.0 ( @braymp  has some machines set up to run 2.8, so I'd like to maintain compatibility for the short-term but abandon it once he gives us the go-ahead).

**Comment by LeeKamentsky** [comment]
There's an additional 3.0 assertion failure on Windows that I'm investigating:

    File "C:\Users\leek\cpdev\cellprofiler\CellProfiler\CellProfiler.py", line 987, in <module>
      main(sys.argv)
    ￼ File "C:\Users\leek\cpdev\cellprofiler\CellProfiler\CellProfiler.py", line 276, in main
      App.MainLoop()
    File "C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py", line 8657, in MainLoop
      wx.PyApp.MainLoop(self)
    File "C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py", line 7952, in MainLoop
      return _core_.PyApp_MainLoop(*args, **kwargs)
    ￼ File "C:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 1385, in DoGetVirtualSize
      return self.DoGetBestSize()
    ￼ File "C:\Users\leek\cpdev\cellprofiler\CellProfiler\cellprofiler\gui\pipelinelistview.py", line 1377, in DoGetBestSize
      for i, item in enumerate(self.items):

    wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\window.cpp(4952) in wxWindow::HandleEraseBkgnd(): unknown background style

**Comment by LeeKamentsky** [comment]
@0x00B1 I had to change some code to make wx 3.0 work on Windows, so I need you to review and merge. There are a couple minor issues (#1561, #1562, #1563) that should be addressed promptly, but IMHO, they shouldn't block the merge.

**Comment by 0x00B1** [comment]
@LeeKamentsky I ran on OS X without issue! :+1:

**Comment by 0x00B1** [comment]
@LeeKamentsky I’ll squash and merge.

**Comment by LeeKamentsky** [comment]
Thx :+1:

**Pull request merged**
