### PR TITLE
Use an inclusive threshold to capture 0 values.

### LINKED ISSUE #2680: MeasureCorrelation: ValueError: zero-size array
MeasureCorrelation apparently doesn't like zero-sized objects.

Running the attached pipeline with the attached images/objects errors with:
```
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.pyc", line 2826, in do_step
  File "cellprofiler\pipeline.pyc", line 2067, in run_module
  File "cellprofiler\modules\measurecorrelation.pyc", line 229, in run
  File "cellprofiler\modules\measurecorrelation.pyc", line 540, in run_image_pair_objects
  File "scipy\ndimage\measurements.pyc", line 581, in sum
  File "scipy\ndimage\measurements.pyc", line 500, in _stats
  File "numpy\core\_methods.pyc", line 29, in _amin
ValueError: zero-size array to reduction operation minimum which has no identity
```
Interesting, I tried to re-create this with the welcome screen pipeline modified to created zero-sized objects, and it worked fine. So there may be something subtle I'm missing.

[issue.zip](https://github.com/CellProfiler/CellProfiler/files/894322/issue.zip)

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #2680 

Could one of @braymp or @apahl please verify this fix?

### CODE REVIEW

**Comment by apahl** [comment]
I have started the pipeline with the fixed version...

**Comment by apahl** [comment]
Thanks for your efforts. However, the fix is not resolving the problem for me, I now get this traceback:
```
Error detected during run of module MeasureCorrelation
Traceback (most recent call last):
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/pipeline.py", line 1763, in
 run_with_yield
    self.run_module(module, workspace)
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/pipeline.py", line 2007, in
 run_module
    module.run(workspace)
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/modules/measurecorrelation.
py", line 228, in run
    object_name)
  File "/host_obscured/home/a/apahl/dev/github/CellProfiler/cellprofiler/modules/measurecorrelation.
py", line 622, in run_image_pair_objects
    RWC1 = np.array(scind.sum(fi_thresh * weight_thresh, labels[combined_thresh], lrange)) / np.array(
  File "/host_obscured/home/a/apahl/conda-envs/cellprof/lib/python2.7/site-packages/scipy/ndimage/me
asurements.py", line 584, in sum
    count, sum = _stats(input, labels, index)
  File "/host_obscured/home/a/apahl/conda-envs/cellprof/lib/python2.7/site-packages/scipy/ndimage/me
asurements.py", line 502, in _stats
    labels.min() < 0 or labels.max() > labels.size):
  File "/host_obscured/home/a/apahl/conda-envs/cellprof/lib/python2.7/site-packages/numpy/core/_meth
ods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
Tue May 16 20:41:08 2017: Image # 3305, module MeasureCorrelation # 8: 38.57 sec
```
I have used the `issues/2680` branch for processing the pipeline.

**Comment by braymp** [comment]
Using the files attached to my OP, the pipeline now works:
image

**Comment by apahl** [comment]
Sorry, it was late yesterday.

I now realize that I still get exactly the same error when using the (now deleted) `issues/2860` branch.

**Comment by mcquin** [comment]
OK. I'll try to recreate the error with your pipeline, and reach out if I
need more information.

**Pull request merged**
