### PR TITLE
morphological operation to distinguish lines from dots (fixes #1556)

### PR DESCRIPTION
**Pull request by 0x00B1**

### CODE REVIEW

**Comment by 0x00B1** [comment]
@LeeKamentsky

**Comment by 0x00B1** [comment]
requires https://github.com/CellProfiler/CellProfiler/pull/1493

**Comment by LeeKamentsky** [comment]
How do the tags to centrosome work? Do we need to tag centrosome and update the tags in requirements.txt?

**Comment by 0x00B1** [comment]
@LeeKamentsky I updated requirements.txt to use `centrosome==1.0.2`.

**Pull request merged**
