### PR TITLE
Add savecroppedobjects to library

### PR DESCRIPTION
**Pull request by callum-jpg**

### CODE REVIEW

**Comment by bethac07** [comment]
Can we have this in maybe a file_processing section of library/functions instead? It's not technically image processing, I think that will help keep us more organized.

Otherwise, looks in pretty good shape!

**Comment by bethac07** [comment]
Need to check if all the test failures are due to this; https://github.com/CellProfiler/core/pull/139#issuecomment-1358228792 - presumably, we need to fix that and then rebase this again

**Comment by callum-jpg** [comment]
In NumPy 1.24 `np.bool` has been removed https://github.com/numpy/numpy/releases/tag/v1.24.0, which is used in centrosome

**Comment by gnodar01** [comment]
https://github.com/CellProfiler/core/pull/140

**Comment by bethac07** [comment]
@callum-jpg please do rebase onto master once #4710 is pulled, thanks!

**Pull request merged**
