### PR TITLE
Documentation - SplitOrMerge

### PR DESCRIPTION
**Pull request by AnneCarpenter**
Makes the meaning of "merge" more clear right up front in the intro help

### CODE REVIEW

**Comment by mcquin** [comment]
@bethac07 I'll let you be the decider on these changes. :) Does this add the clarity you'd like around the definition of "merge"?

**Comment by AnneCarpenter** [comment]
bump @bethac07

**Comment by AnneCarpenter** [comment]
@0x00b1 I think you can merge this PR

**Comment by 0x00b1** [comment]
Thanks, @AnneCarpenter.

**Pull request merged**
