### PR TITLE
Documentation - MeasureObjectSizeShape

### PR DESCRIPTION
**Pull request by AnneCarpenter**
Some help please:
1) Please someone verify line 71 where I added centroid - is it true? And/or, can anyone elaborate on why it's different than LocationX from Identify?
2) see change max to min in line 102, correct?

### CODE REVIEW

**Comment by bethac07** [comment]
Someone mathier than me should weigh in on the centroid thing as I think it's not correct but I'm not certain (the definition we report here for how we report center (furthest from any edge) doesn't match the definitions of centroid I'm finding but I'm not sure if that means anything).  FWIW we do say in IPO that we ARE measuring the centroid there (the center of mass of the binary representation), and we say that the center reported in MeasureObjectSizeShape is different than the one in IPO.  

I don't think your change to 102 is right; I don't know why the MaximumRadius would be 1/2 of the _minimum_ width.

**Comment by AnneCarpenter** [comment]
Agreed with Beth, line 102 should be reverted.

**Comment by mcquin** [comment]
Interesting! It can't find *MeasureObjectSizeShape* and yet it's there.

I'll dig into this tomorrow morning.

**Comment by AnneCarpenter** [comment]
Weird! See if you want to also delete the one sentence for #3155 at the same time. I'm nervous to touch anything!

**Comment by mcquin** [comment]
Derp. It failed to load the module because it couldn't find the global variable `No` (note the "o" isn't capitalized). I've fixed it and removed the sentence for #3155

**Comment by AnneCarpenter** [comment]
nice catch!

**Pull request merged**
