### PR TITLE
Compute features when data is available

### LINKED ISSUE #2764: MeasureCorrelation should safely compute measurements
There are a couple code paths which aren't robust to empty data:

1. [RWC coefficient](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/measurecorrelation.py#L621-L625)
1. [Overlap coefficient](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/measurecorrelation.py#L621-L625)

When any of the inputs are `[]`, the following error occurs:

```
Worker 0: Error detected during run of module MeasureCorrelation#8
Worker 0: Traceback (most recent call last):
Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 1900, in run_image_set
Worker 0:     self.run_module(module, workspace)
Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/pipeline.py", line 2007, in run_module
Worker 0:     module.run(workspace)
Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/modules/measurecorrelation.py", line 228, in run
Worker 0:     object_name)
Worker 0:   File "/Users/mcquin/code/CellProfiler/CellProfiler/cellprofiler/modules/measurecorrelation.py", line 665, in run_image_pair_objects
Worker 0:     fpsq = scind.sum(first_pixels[combined_thresh] ** 2, labels[combined_thresh], lrange)
Worker 0:   File "/usr/local/lib/python2.7/site-packages/scipy/ndimage/measurements.py", line 584, in sum
Worker 0:     count, sum = _stats(input, labels, index)
Worker 0:   File "/usr/local/lib/python2.7/site-packages/scipy/ndimage/measurements.py", line 502, in _stats
Worker 0:     labels.min() < 0 or labels.max() > labels.size):
Worker 0:   File "/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
Worker 0:     return umr_minimum(a, axis, None, out, keepdims)
Worker 0: ValueError: zero-size array to reduction operation minimum which has no identity
```

Related issue: #2680

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #2764

### CODE REVIEW

**Comment by mcquin** [comment]
@apahl - I'm very sorry for the delay on getting this through. Could you please check if this resolves your issue from https://github.com/CellProfiler/CellProfiler/issues/2680 ? Thanks!

**Comment by apahl** [comment]
Pipeline is running...

**Comment by 0x00b1** [comment]
Nice! Thanks, @apahl.

**Comment by apahl** [comment]
What I meant was that I had started the pipeline. It takes 4.5 h to finish on our cluster... ;-)  
But in the meantime it has indeed finished without errors and produced all expected results.

Thanks a lot for your efforts in fixing this!!

Kind regards,  
Axel

**Comment by 0x00b1** [comment]
LOL! Thanks for the clarification @apahl. 😄

**Pull request merged**
