### PR TITLE
fix typos for "Alcian"

### PR DESCRIPTION
**Pull request by dlogan**
https://en.wikipedia.org/wiki/Alcian_blue_stain

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
Unfortunately, you need to fix upgrade_settings to look for the old spelling and change it to the new one and ideally, add a test case for that as well.

**Comment by dlogan** [comment]
Ah, ok.  Not that important, so I will add do this maybe on coding day.

**Comment by 0x00B1** [comment]
@dlogan What’s going on with this?

**Comment by dlogan** [comment]
Oh, I didn't have time for this, and won't for awhile.   Admittedly, I don't think I've never modified upgrade_settings and my test case creation skills are lame. I'd be glad to have help :wink:

**Comment by LeeKamentsky** [comment]
IMHO the fix is not urgently needed and either the branch or pull request can serve as documentation for what I need to do to resolve. Can we leave the pull request open and I'll get to it sooner or later?

**Comment by dlogan** [comment]
Indeed!  No one else ever pointed this typo out, so it can wait.

**Comment by 0x00B1** [comment]
@LeeKamentsky and @dlogan bump

**Comment by AnneCarpenter** [comment]
Sounds like it's not a priority to fix this under the circumstances. What is the procedure from here, so the partially functional pull request doesn't linger forever? Just "close"?

**Pull request closed without merging**
