### PR TITLE
New GUI for selecting multiple image and object sets

### LINKED ISSUE #2298: Change "Add another image/object" dropdowns to MultiChoice windows
Beth @bethac07 had a lovely usability improvement idea that would not be rocket science to implement. 

We were lamenting the many modules that offer "Add another image" and "Add another object"... the buttons themselves are pretty chunky and there are not obvious visual cues for each set of settings that relate to each image/object so overall this gets pretty ugly especially when you have multiple images and objects specified in the same module. We are guessing the code that enables this behavior is complex, too.

She suggested switching to `cps.MultiChoice`. An example is in MeasureTexture ("Angles to measure"). This way, there is a single chunk of real estate devoted to choosing images, and you can readily choose all/some images by command-clicking.

In our case, it would be nice for cps.MultiChoice to expand to fit its contents up to say ~10 or so (given a pipeline will typically have a manageable number of images/objects; it's weird to interact with the cps.MultiChoice element when you can only see 3 items in the tiny window).

Current situation (with two images chosen so far):
addimage

Proposed look (from MeasureTexture, with 2 items chosen):
multichoice

(Caution: this may not be feasible for all modules/situations; for example if there are a series of subsequent unique choices to be made for each image/object. Thus the first step towards accomplishing this goal is to itemize which cases can be handled this way.)

### PR DESCRIPTION
**Pull request by DavidStirling**
Continuing from #3938 but with a cleaner branch. Closes #2298.

This pull request will replace the interface for selecting multiple image or object sets in the measurement modules. Previously multiple objects were typically added using groups, with an 'Add an image' button allowing the user to choose an additional image from a dropdown box. This was slow and tedious when working with many images. The new implementation uses checklist boxes. I've also added a right-click menu for 'select all/none' functionality. To preserve functionality items are also labelled with their source module, and annotated appropriately if they're missing from the pipeline (screenshot below).

NewMultiSubscriberHandling

Per Anne's comments, I've tried to make as much use of this as possible to keep things consistent between modules. Changed modules are as follows:

- MeasureColocalization
- MeasureGranularity
- MeasureImageAreaOccupied
- MeasureImageIntensity
- MeasureImageQuality
- MeasureObjectIntensity
- MeasureObjectIntensityDistribution
- MeasureObjectSizeShape
- MeasureTexture

MeasureObjectIntensityDistribution still uses groups for object sets since each needs an individually defined center point.

**Compatibility notes**:

I've made it so that selected image and object sets are converted when importing older pipelines. However, with MeasureGranularity we decided to move from having detection parameters configured per-image to having a single set of parameters shared between all images. In practice most users did this anyway, but when importing old pipelines where multiple sets of parameters were defined CellProfiler will now carry forward the first set and log a warning about the upgrade. Multiple copies of a module can be used to specify multiple sets of analysis parameters. 

Likewise, MeasureImageIntensity now no longer operates on pairs of images and objects, instead all possible image/object pairings will be processed together. Upgrading an old pipeline will build a list featuring all images and objects and log a warning about this change. This could create more computational work, but again a user could duplicate the module to do specific pairwise comparisons.

**Other notes**:

This implementation adds the ListImageNameSubscriber and ListObjectNameSubscriber setting classes to setting.py. This is basically a wx listbox but with checkboxes next to each name to aid selection, which seems to be much easier to use than SubscriberMultiChoice (which has existed for a long time but is rarely utilised, and needed ctrl+clicking to select multiple options). SubscriberMultiChoice is still used in ExportToDatabase but has otherwise been replaced, if we want to remove that class entirely then we could update ExportToDatabase too with a bit of effort.

It's worth mentioning that the large boxes introduced by this change will make the text wrapping bug described in #3962 more noticeable. We might want to try to fix that.

### CODE REVIEW

**Comment by DavidStirling** [comment]
Point of interest - I know the font spacing between items and their source modules is not perfect. This is because wx's default fonts are not fixed pitch. I can make it align more nicely, but the result is a less attractive font (see screenshot below). I'm open to either option but went with the default fonts because I feel it's easier to read and you can fit a much longer name without needing scrollbars.

ListboxAlt

**Comment by bethac07** [comment]
Spacing, etc looks really bad on Mac; I don't think we can/should pull this without fixing that 
image

**Comment by bethac07** [comment]
(Sorry! Otherwise I'm super in favor)

**Comment by DavidStirling** [comment]
Wow, thanks for checking that! That's really weird, it looks like on mac something is adding spacing between the checkbox and the actual text.

**Pull request closed without merging**
