### PR TITLE
Updating ExpandOrShrink with additional measurement feature to cellprofiler.library

### PR DESCRIPTION
**Pull request by callum-jpg**
This PR supersedes #4537

### CODE REVIEW

**Comment by bethac07** [comment]
@callum-jpg This is currently failing because a core pr has been pulled that is now breaking unrelated tests. If you rebase off of the just-now-current master, that should fix it.

**Comment by bethac07** [comment]
(Otherwise LGTM, but I'll leave the official PR approval to the experts ;) )

**Comment by gnodar01** [comment]
Resolves #4519

**Comment by gnodar01** [comment]
Should #4519 be filed in the 4.2.2 project?

**Review by gnodar01 — APPROVED** [review]

**Pull request merged**
