### PR TITLE
Update dependencies for CP2.2

### LINKED ISSUE #3481: Pin dependencies for stable branch
Hi,

I've been running into a number of different issues trying to install CellProfiler in different ways. I'm not sure if they're related, but I'm posting them here in one thread in hopes of elucidating the issue.

Note: I'm running Python2.7 and Ubuntu 16.04.

**First method (installing from PyPl):**
```
pip install --pre --user cellprofiler
cellprofiler
```

```
Traceback (most recent call last):
  File "/home/ben/.local/bin/cellprofiler", line 11, in <module>
    sys.exit(main())
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/__main__.py", line 152, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/gui/app.py", line 55, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/gui/app.py", line 58, in OnInit
    import cellprofiler.gui.cpframe
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/gui/cpframe.py", line 8, in <module>
    import cellprofiler.gui.datatoolframe
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/gui/datatoolframe.py", line 8, in <module>
    import cellprofiler.gui.moduleview
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/gui/moduleview.py", line 2818, in <module>
    class FileCollectionDisplayController(object):
  File "/home/ben/.local/lib/python2.7/site-packages/cellprofiler/gui/moduleview.py", line 2852, in FileCollectionDisplayController
    cellprofiler.icons.get_builtin_image("microscope-icon_16").ConvertToBitmap())
  File "/usr/lib/python2.7/dist-packages/wx/_core.py", line 3646, in ConvertToBitmap
    return _core_.Image_ConvertToBitmap(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "image.IsOk()" failed at ../src/gtk/bitmap.cpp(626) in wxBitmap(): invalid image
```

**Second Method (install master branch from git):**
```
pip install --user --editable .
cellprofiler
```

```
(cellprofiler:8867): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
Traceback (most recent call last):
  File "/home/ben/.local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')()
  File "/home/ben/repos/CellProfiler/cellprofiler/__main__.py", line 152, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/app.py", line 55, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/app.py", line 64, in OnInit
    self.frame.start(self.workspace_path, self.pipeline_path)
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/cpframe.py", line 350, in start
    self.__pipeline_controller.start(workspace_path, pipeline_path)
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 191, in start
    self.do_create_workspace()
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 657, in do_create_workspace
    self.__pipeline.clear()
  File "/home/ben/repos/CellProfiler/cellprofiler/pipeline.py", line 2382, in clear
    self.notify_listeners(PipelineClearedEvent())
  File "/home/ben/repos/CellProfiler/cellprofiler/pipeline.py", line 3188, in notify_listeners
    listener(self, event)
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 1421, in __on_pipeline_event
    self.on_image_set_modification()
  File "/home/ben/repos/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 1432, in on_image_set_modification
    self.__workspace.invalidate_image_set()
  File "/home/ben/repos/CellProfiler/cellprofiler/workspace.py", line 497, in invalidate_image_set
    self.save_pipeline_to_measurements()
  File "/home/ben/repos/CellProfiler/cellprofiler/workspace.py", line 480, in save_pipeline_to_measurements
    self.measurements.add_experiment_measurement(M_PIPELINE, fd.getvalue())
  File "/home/ben/repos/CellProfiler/cellprofiler/measurement.py", line 522, in add_experiment_measurement
    self.hdf5_dict.add_all(EXPERIMENT, feature_name, [data], [0])
  File "/home/ben/repos/CellProfiler/cellprofiler/utilities/hdf5_dict.py", line 792, in add_all
    maxshape=(None, 3))
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 105, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 76, in make_new_dset
    if isinstance(chunks, tuple) and (-numpy.array([ i>=j for i,j in zip(tmp_shape,chunks) if i is not None])).any():
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
```

**Third Method (installing stable branch from git):**
```
pip install --user --editable .
cellprofiler
```

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/ben/.local/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')()
  File "/home/ben/repos/CellProfiler/cellprofiler/__main__.py", line 175, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/home/ben/repos/CellProfiler/cellprofiler/utilities/cpjvm.py", line 3, in <module>
    import javabridge
  File "/usr/local/lib/python2.7/dist-packages/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
ImportError: numpy.core.multiarray failed to import
```

This last error, I believe, is caused by a conflict of numpy and javabridge versions. When I install the stable branch of cellprofiler via pip, it reverts my version of numpy to 1.11.3, which is apparently not the version used to compile javabridge (1.0.15).

I've been trying to figure these issues out for a while now, but can't seem to make it beyond this point for any of these installation methods. Any help would be greatly appreciated! Thanks!

### PR DESCRIPTION
**Pull request by AetherUnbound**
Resolves #3481 
This allows CellProfiler 2.2 to be pip installed with the newer versions of javabridge and numpy. Unfortunately, CP 2.2 uses wxPython v2.8, which is no longer available in normal distribution channels. It can still be compiled from source should users require it, but we won't be able to build this newer version of 2.2 (2.2.2?) for our own redistribution. We can definitely tag this version though.

### CODE REVIEW

**Comment by mcquin** [comment]
@bethac07 Great point. Let's get that version information from @minh-doan :)

**Comment by minh-doan** [comment]
Oh, he's here !

He tested CP2 vs 3 with the following 2 sets of dependencies:
1/New set : centrosome-1.0.9, prokaryote-2.3.2, python-bioformats-1.3.2
2/Old set : centrosome-1.0.4, prokaryote-1.0.11, python-bioformats-1.0.9

**Comment by mcquin** [comment]
Thanks @minh-doan! Which set of dependencies had the best performance?

**Comment by mcquin** [comment]
Thanks for the input @minh-doan! 

@AetherUnbound and I feel it's better for the dependencies to be as up to date as allowable. We'll keep the dependency set as-is.

**Pull request merged**
