### PR TITLE
Retrieve prokaryote-*.*.*.jar during setup

### PR DESCRIPTION
**Pull request by 0x00B1**

### CODE REVIEW

**Comment by 0x00B1** [comment]
@LeeKamentsky Feedback?

**Comment by LeeKamentsky** [comment]
@0x00B1 I looked the pull request at it's current state  - the code is OK, but CellProfiler.py, windows_setup.py and setup.py all use the function, "fetch_external_dependencies". There's more work to do before we can run CP from this branch - once you can run `python CellProfiler.py` and have it display the GUI, then I'll look at it again.

**Comment by 0x00B1** [comment]
uh, ok

**Comment by 0x00B1** [comment]
@LeeKamentsky Jenkins approves. :+1:

**Pull request merged**
