### PR TITLE
revert changes to object count method

### PR DESCRIPTION
**Pull request by bethac07**

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Has this been confirmed to resolve the indexing issue?

**Comment by AetherUnbound** [comment]
I think this will cause a regression on #3541. This is totally fine (I think my change caused many more problems than it solved), I just want to make note of it here!

**Comment by bethac07** [comment]
It does seem to fix the issue, and it does indeed re-break 3541.  I'll reopen that.

**Comment by AetherUnbound** [comment]
LGTM though! Again, my naïveté with this codebase I think caused more damage than good in that PR lol. I will go through and find another solution to that particular issue!

**Pull request merged**
