### PR TITLE
Create ErodeObjects, rename Erosion to ErodeImage

### PR DESCRIPTION
**Pull request by DavidStirling**
Requires CellProfiler/core#22

We had DilateImage and DilateObjects modules, but only Erosion (which only supported images). ExpandOrShrinkObjects is generally better but only works in 2D, so we lacked a pathway for shrinking 3D objects. I've therefore renamed Erosion to ErodeImage and created ErodeObjects.

Another difference is that ErodeObjects will completely remove a tiny object, but ExpandOrShrink will always preserve 1 pixel. That gives it a slightly different use case even in 2D.

### CODE REVIEW

**Comment by braymp** [comment]
I could foresee single-pixel object removal producing a problem for downstream modules (or perhaps our intuitive assumptions). Is there a way to preserve ExpandOrShrink's behavior on this score?

**Comment by 0x00b1** [comment]
> I could foresee single-pixel object removal producing a problem for downstream modules (or perhaps our intuitive assumptions). Is there a way to preserve ExpandOrShrink's behavior on this score?

Because objects would be reindexed? (Hi, @braymp ! I hope you're doing okay during this weird time!)

**Comment by DavidStirling** [comment]
I thought that might be a potential issue, but wasn't able to trigger an error when playing with it. It's largely using the default ObjectProcessing functions, so I don't think everything gets relabelled afterwards.

Replicating the ExpandOrShrink functionality would be a bit more complicated. Right now we just use skimage's dilate and erode functions in these modules.

**Comment by braymp** [comment]
I think I've had cases where an inadvertently missing object may break any 1:1 object relationship assumptions, e.g., ExportToSpreadsheet where you can horizontally concatenate primary/secondary/tertiary object tables and the like.

**Comment by DavidStirling** [comment]
I can imagine a couple of options here:

- Relabel the objects before adding the eroded object set to the sets list.

- Make a record of the centroid of each label and add those back in after dilation, so as to preserve all objects in the same manner as ExpandOrShrink

Could either of these work?

**Comment by braymp** [comment]
I'm leaning towards the latter, perhaps an option to "Do not remove objects post-erosion" (yes/no)?

**Comment by DavidStirling** [comment]
I started adding that feature and then realised that the Skimage erosion filter is actually not going to work on a segmentation image. It treats the labels as intensities and therefore ends up inappropriately changing touching objects. I'll have to rework this.

**Comment by DavidStirling** [comment]
Okay, I've reworked this to process objects individually and added options for preserving midpoints and relabelling the resulting array.

**Pull request closed without merging**
