### PR TITLE
3 d/measureimageoverlap

### PR DESCRIPTION
**Pull request by vchernys**

### CODE REVIEW

**Comment by 0x00b1** [comment]
@vchernys Would you mind resolving the merge conflicts?

**Comment by 0x00b1** [comment]
@vchernys (and @AnneCarpenter) should we merge this before 3.0.0?

**Comment by vchernys** [comment]
@0x00b1 I think merging this prior to release of 3.0 will be useful but it is up to you and @AnneCarpenter

**Comment by AnneCarpenter** [comment]
I think it's worthwhile, given that a module cannot break all of CP. The module may not be perfect but we know we need it for demonstrating/validating CP's 3D capabilities.

**Pull request merged**
