### PR TITLE
Pony

### PR DESCRIPTION
**Pull request by LeeKamentsky**
Probably best not to merge this one. But you are welcome to try it out.

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
Now it's safe and easter eggy.

**Comment by braymp** [comment]
This is literally the best thing ever.

**Comment by dlogan** [comment]
A perfect sound, as Lee rides off into the sunset 🌅 👋

**Comment by LeeKamentsky** [comment]
It might be more useful if it's at the end of the analysis instead of at
the start. Feel free to change ;-)

**Comment by daviddao** [comment]
Most amazing thing ever. Lee is going with style :sunglasses:

**Pull request merged**
