### PR TITLE
Add advanced settings toggle to IdentifyPrimaryObjects (resolves #2577)

### LINKED ISSUE #2577: Advanced settings toggle for IdentifyPrimaryObjects

### PR DESCRIPTION
**Pull request by mcquin**
screen shot 2017-02-09 at 4 22 47 pm
screen shot 2017-02-09 at 4 23 04 pm

### CODE REVIEW

**Comment by mcquin** [comment]
@bethac07 The lower screenshot shows the defaults used when "No" is selected for "Use advanced settings?". Can you please 👍 or 👎  those?

**Comment by dlogan** [comment]
All defaults look ok to me, except I might question is the "Fill holes in identified objects?" = "After both thresholding and declumping".  It has been the default for awhile, and so perhaps I should file a separate issue, but I have had this setting give me IMHO spurious segmentation.  It usually improved (according to my intuition) once I changed the setting to "After thresholding only."  I know this is vague and I can't point to any examples offhand, but I wonder if anyone else has encountered this? @braymp @bethac07 @karhohs

**Comment by dlogan** [comment]
Example from Welcome screen pipeline.

Default = "After both thresholding and declumping"
screen shot 2017-02-10 at 4 10 05 pm

Changed to "After thresholding only."
screen shot 2017-02-10 at 4 09 46 pm

The gaps in the middle of the clumped areas filled in (incorrectly, imho) with the default.

**Comment by mcquin** [comment]
Whoa that second image looks way better!! I'm going to create a new issue and we can continue the conversation there. :)

**Pull request merged**
