### PR TITLE
patch for issue #1553 - error from classifyobjects

### PR DESCRIPTION
**Pull request by erexhepa**

### CODE REVIEW

**Comment by erexhepa** [comment]
Hi I selected release 2.1.1 for the pull request as it is the latest stable release.

**Comment by LeeKamentsky** [comment]
Elton, do you have a branch that you're looking to merge? It looks like the PR hasn't properly selected the source and target.

**Comment by erexhepa** [comment]
I wanted to create a pull request so that I can commit the changes to fix the problems with the measurecorrelation module (issue #1553). 

I saw that release_2.1.1 had the last commit you did so I thought to integrate the changes into that branch. isn't this the branch to merge?

Elton

**Comment by LeeKamentsky** [comment]
Our practice is something like this:

    git checkout master
    git pull origin master
    git checkout -b issues/1553
    .... fix code ...
    git add ...
    git commit -m "Fixes #1553 comment"
    .... merge to or rebase on master if master has changed...
    git push origin issues/1553 (or in your case, pushing to your fork is just fine)
    ... create pull request...

release_2.1.1 is for patches to the 2.1.1 release if they are ever needed and the pull request is asking for us to merge every change since that release from master to the release branch, so not so appropriate.

Do you have a commit that has the fix? I can do `git cherry-pick` to pick it up if so.

**Comment by erexhepa** [comment]
sorry, I have forked the master branch and committed my latest changes. I will create a pull request from my forked version

**Comment by LeeKamentsky** [comment]
Alternate PR of same code accepted

**Pull request closed without merging**
