### PR TITLE
Issue #1550 - new morphological code to distinguish lines from dots

### PR DESCRIPTION
**Pull request by tischi**
Hi Lee,
this adds code to add a morphological filter that can separate linear structures from dot-like structures.
Best, Tischi

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
It looks pretty good in general - I will write unit tests on the final stuff, but want to wait until we finish our discussion before going further than that.

**Comment by tischi** [comment]
Hi Lee,

independent of whether we also want to add some code to
EnhancerOrSuppressFeatures I think we could add the code to morph. For
instance the tophat filter is also present in morph and again as Enhance
Speckles.

i think this is good in general to have things twice with different names
as it makes them findable  for both biologists and image analysis people.

Tischi


_____________________________
*Dr. Christian Tischer*
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Comment by AnneCarpenter** [comment]
Agree.

**Comment by LeeKamentsky** [comment]
Thx guys. I am going to put off work on this until Friday (tied up in a conference Tues, Wed, and Thurs)  , so you shouldn't mistake inactivity for disinterest. I'll add to the branch after that.

**Comment by 0x00B1** [comment]
@tischi we’ve moved cpmath into a separate package:

https://travis-ci.org/CellProfiler/centrosome

I’ll make the required changes to your pull request and try to merge today.

**Comment by LeeKamentsky** [comment]
K - maybe the best approach is to take take the pull request and file an issue to add the unit tests. Anne just said she wants to use the code in a project for one of our collaborators.

**Comment by AnneCarpenter** [comment]
Yes, @jhung0 wants to try it out.

**Comment by 0x00B1** [comment]
https://github.com/CellProfiler/CellProfiler/pull/1623

https://github.com/CellProfiler/centrosome/pull/37

**Comment by tischi** [comment]
Hi all,

thanks for taking my code. this is exciting :)

Tischi


_____________________________
*Dr. Christian Tischer*
Advanced Light Microscopy Facility
EMBL Heidelberg
Meyerhofstr.1
D - 69117 Heidelberg
Phone +49(0)6221 387-8951
www.embl.de/almf

**Pull request closed without merging**
