### PR TITLE
Replace measurement-based ExportToDB state transmission with shared_state implementation

### PR DESCRIPTION
**Pull request by gnodar01**
Seems in addition to the other fix mentioned in #4805, it also fixes the issue #4695 solved. I've rebased this on master and also reverted the changes made there.

### CODE REVIEW

**Comment by gnodar01** [comment]
This supersedes #4805, so pasting @DavidStirling to reduce potential confusion:

Requires https://github.com/CellProfiler/core/pull/147

Fixes https://github.com/CellProfiler/CellProfiler/issues/4717

Seeing people posting errors revolving around the faux measurements we used to fix https://github.com/CellProfiler/CellProfiler/issues/3991 makes me sad.

To summarise, we needed to make a note of how many channels were in each image the user wanted to be listed in their CPA properties file. The problem was that we make that file after the run ends and workers shut down. At that point we don't have access to image providers and so needed to make a note of how many channels were in an image during the run. This was done by creating 'hidden' measurements to record that information, but some naughty modules still tried to grab those measures. There were also some rare settings combinations which would trip up the measurement generator.

Measurements were never an ideal solution to passing info between pipeline phases. With module state now working properly we can use that instead for a much cleaner fix.

**Comment by gnodar01** [comment]
@bethac07 requesting you as reviewer since I (re)constructed this PR.

LGTM, but worth you taking a very quick look here, and in the corresponding CellProfiler/core#147, in case there is something in the ancient knowledge that I would overlook but catches your eye.

**Comment by bethac07** [comment]
LGTM also but should probably test it out in practice - should be able to do in the background today, if you haven't already. 

> in case there is something in the ancient knowledge that I would overlook but catches your eye

Cracks about my age? Harsh but fair ;)

**Comment by bethac07** [comment]
@DavidStirling , do you happen to remember, what data were we using to test this property file functionality that it actually did what it was supposed to? I just tried the PR and built 4.2.6 on a color image (built off of the UntangleWormsBrightfield example, but then simplified just in case that was why the pipeline was cranky) and in both cases, it's giving an identical properties file but it's wrong (says that channels_per_image is 1, image_channel_colors are gray, no blend modes, etc).

**Comment by bethac07** [comment]
Nevermind, error was between keyboard and chair on my side- I was accidentally not running this PR (forgot I had CellProfiler aliased on terminal). 4.2.6 (built or source, can now confirm) is NOT doing the right thing, so I must have screwed it up in #4695 , but this does!

**Review by bethac07 — APPROVED** [review]

**Comment by bethac07** [comment]
#4695 was I guess just pulled, so probably NOT what screwed it up, but something did along the way in one of these commits. In any case, probably not worth tracking down at this stage!

image

**Pull request merged**
