### PR TITLE
Create cellprofiler/VERSION

### LINKED ISSUE #2494: Nightly build error: pkg_resources.DistributionNotFound
```
Traceback (most recent call last):
  File "/CellProfiler.app/Contents/Resources/__boot__.py", line 81, in <module> 
    _run()
  File "/CellProfiler.app/Contents/Resources/__boot__.py", line 62, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/CellProfiler.app/Contents/Resources/CellProfiler.py", line 1, in <module>
    import cellprofiler.__main__
  File "/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/__init__.py", line 8, in <module>
    __version__ = pkg_resources.get_distribution("cellprofiler").version
  File "pkg_resources/__init__.pyc", line 561, in get_distribution
  File "pkg_resources/__init__.pyc", line 441, in get_provider
  File "pkg_resources/__init__.pyc", line 962, in require
  File "pkg_resources/__init__.pyc", line 849, in resolve
pkg_resources.DistributionNotFound: The 'cellprofiler' distribution was not found and is required by the application
```

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #2494

### CODE REVIEW

**Comment by mcquin** [comment]
@0x00b1 ready for review

**Comment by 0x00b1** [comment]
Do you know about `pkg_resources.get_distribution("CellProfiler").version`?

**Comment by 0x00b1** [comment]
@mcquin Oops. Missed the issue.

**Comment by 0x00b1** [comment]
Regardless, we should package “pkg_resources” since it’s useful.

**Comment by mcquin** [comment]
@0x00b1 I tried `pkg_resources.get_distribution("CellProfiler")[0].version`, but it raised the same error as before.

**Pull request merged**
