### PR TITLE
Create setting cellprofiler.setting.StructuringElement

### LINKED ISSUE #2266: Setting for structuring element

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #2266 

Preview:
structuring element

### CODE REVIEW

**Comment by 0x00b1** [comment]
Nice

**Comment by 0x00b1** [comment]
h_and_v_and_window_and_5e92039e-702e-11e6-9728-36ae0b7ff6de_png__png_image__364 x 64_pixels_

**Comment by mcquin** [comment]
@0x00b1 You should probably register your application.

**Comment by 0x00b1** [comment]
LOL

**Pull request merged**
