### PR TITLE
refactored cellprofiler.cpmath into a unique package

### PR DESCRIPTION
**Pull request by 0x00B1**
Refactored into https://github.com/cellprofiler/centrosome

### CODE REVIEW

**Comment by 0x00B1** [comment]
@LeeKamentsky This is ready for review. :fireworks: :

**Comment by LeeKamentsky** [comment]
Centrosome looks good - nice to have it prebuilt. Changes to files look like a straightforward redirect of the imports. The tutorials probably break as do any 3rd party plugins using cellprofiler.cpmath. Does it make sense to have some sort of legacy support for `import cellprofiler.cpmath.cpmorphology` and similar (with a deprecation warning)?

**Comment by 0x00B1** [comment]
> Does it make sense to have some sort of legacy support for import cellprofiler.cpmath.cpmorphology and similar (with a deprecation warning)?

Great idea. I’ll do this.

**Comment by LeeKamentsky** [comment]
@0x00B1  look at https://github.com/CellProfiler/CellProfiler/tree/leek/1490 and 73000c3. The idea is to use __name__ and the fact that the module is in the sys.module dictionary from the start to find the module and copy stuff from the similarly-named module in centrosome. It works is all I'll say for it.

Merge my changes if you want and after that, fine with me to merge to master if it is with you.

**Comment by 0x00B1** [comment]
I need to fix centrosome’s packaging. Go figure. :laughing:

**Comment by 0x00B1** [comment]
@LeeKamentsky What do you think?

**Pull request merged**
