### PR TITLE
Fixes #1627: Guild the lilly until it sinks

### LINKED ISSUE #1627: Can't load deprecated cellprofiler.cpmath modules
There's a typo in cellprofiler/cpmath/__init__.py that prevents loading centrosome using cellprofiler.cpmath. Will have fix momentarily.

### PR DESCRIPTION
**Pull request by LeeKamentsky**
Conflicts:
	cellprofiler/cpmath/__init__.py
	cellprofiler/cpmath/bg_compensate.py
	cellprofiler/cpmath/cpmorphology.py
	cellprofiler/cpmath/filter.py
	cellprofiler/cpmath/haralick.py
	cellprofiler/cpmath/index.py
	cellprofiler/cpmath/lapjv.py
	cellprofiler/cpmath/otsu.py
	cellprofiler/cpmath/outline.py
	cellprofiler/cpmath/princomp.py
	cellprofiler/cpmath/propagate.py
	cellprofiler/cpmath/radial_power_spectrum.py
	cellprofiler/cpmath/rankorder.py
	cellprofiler/cpmath/smooth.py
	cellprofiler/cpmath/tests/__init__.py
	cellprofiler/cpmath/threshold.py
	cellprofiler/cpmath/watershed.py
	cellprofiler/cpmath/zernike.py

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
@0x00B1 I forgot to include 73000c36ea679485058c888393be602eb46d3318 when addressing #1490. There's a bug in cellprofiler.cpmath.__init__ and this is better and even has unit tests for the imports and their deprecation.

**Comment by 0x00B1** [comment]
Why did you modify __init__.py?

**Comment by 0x00B1** [comment]
Actually, why did you modify any of the existing files?

**Comment by LeeKamentsky** [comment]
I modified __init__ because of this: https://github.com/CellProfiler/CellProfiler/blob/aabaae1254b054dfe7fa4a83a349dc5f6af2d49a/cellprofiler/cpmath/__init__.py#L10

    def bind(module):
        module = sys.modules[module]
        k = module.rsplit(".")[-1]

The minimal fix would be:

    def bind(module):
        k = module.rsplit(".")[-1]
        module = sys.modules[module]

but I realized that I had made and tested that fix in https://github.com/CellProfiler/CellProfiler/commit/73000c36ea679485058c888393be602eb46d3318, so instead of redoing the fix, I did a cherry-pick which needed a bit of work because of the rebase. If you want, I can do the minimal change and add the test and that would be enough.

**Comment by 0x00B1** [comment]
:+1: for a minimal change.

**Comment by LeeKamentsky** [comment]
@0x00B1 minimal change

**Comment by 0x00B1** [comment]
Awesome

**Comment by 0x00B1** [comment]
Perfume has been thrown and ice has been smoothed!

**Pull request merged**
