### PR TITLE
Fixes #1767 by persisting the dialog size

### LINKED ISSUE #1767: Make a bigger window for Test menu > "Choose image set"
The window created by clicking the menu "Test" (mode) > "Choose image set" is invariably too small.  I always resize it bigger in both dimensions. It's modal, so it should be a problem to be much bigger, and it would be cool to have it resize smartly, relative to the Main window GUI or the monitor. 

image

### PR DESCRIPTION
**Pull request by LeeKamentsky**
@dlogan this remembers the size of the "Choose image set" dialog. Hit the merge button if you like.

### CODE REVIEW

**Comment by 0x00B1** [comment]
:+1: 

(I’ll merge when Travis is finished.)

**Comment by 0x00B1** [comment]
@LeeKamentsky A few tests failed https://travis-ci.org/CellProfiler/CellProfiler/builds/109687491

**Comment by LeeKamentsky** [comment]
@0x00B1 investigating now

**Comment by LeeKamentsky** [comment]
@0x00b1 Needed merge to master to pick up fixes related to possible missing URLs.

**Comment by 0x00B1** [comment]
@LeeKamentsky nice

**Pull request merged**
