### PR TITLE
Global Gray-level Thresholding Based on Object Size

### PR DESCRIPTION
**Pull request by PetterRanefall**
SizeIntervalPrecision
Object Feature based Gray-level Thresholding using optimized global precision.
Computes the threshold level that optimizes the golbal precision with regards to a given expected object size range.
Incorporated into ApplyThreshold, IdentifyPrimaryObjects, IdentifySecondaryObjects.
By Petter Ranefall 2016.
"Global Gray-level Thresholding Based on Object Size", Cytometry Part A, 89:4, 2016, pp. 385-390.

### CODE REVIEW

**Comment by 0x00b1** [comment]
Hi, @PetterRanefall! Thanks for the pull request.

Would you mind rebasing? This clobbers the diff.

**Comment by PetterRanefall** [comment]
I rebased and updated applythreshold.py and identify.py.

**Comment by 0x00b1** [comment]
@PetterRanefall Hrm. Your diff is still messed up. How did you make your patch?

**Comment by PetterRanefall** [comment]
It went a little too fast yesterday, sorry. Now I have updated identify.py with some missing lines and it runs on my local machine.

**Comment by 0x00b1** [comment]
This has been moved to Centrosome.

**Pull request closed without merging**
