### PR TITLE
Change inplace operation (resolves #2156)

### LINKED ISSUE #2156: Workspace viewer: Error on adding object
When adding an object to a workspace viewer overlay, I encountered the following error:

```
Traceback (most recent call last):
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\viewworkspace.py", line 93, in on_check_change
    self.vw.redraw()
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\viewworkspace.py", line 662, in redraw
    self.frame.figure.canvas.draw()
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 51, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\figure.py", line 1159, in draw
    func(*args)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2324, in draw
    a.draw(renderer)
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\cpartists.py", line 733, in draw
    om.points.set_axes(self.axes)
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\cpartists.py", line 258, in points
    color = self.color)
  File "C:\Users\brayma2\Desktop\github\branches\2.2.0\cellprofiler\gui\cpartists.py", line 1160, in __init__
    pts += .5          # Target the centers of the pixels.
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint32') with casting rule 'same_kind'
```

I know the WSViewer is currently MIA so I'm putting this here for when it eventually returns.

### PR DESCRIPTION
**Pull request by bethac07**
Implements Mark's solution from that issue.

### CODE REVIEW

**Comment by braymp** [comment]
Oh yay!

Any idea whether this change needs to be made elsewhere in the code base?

**Comment by bethac07** [comment]
None whatsoever, but at least we should fix it in this one spot.

**Comment by 0x00b1** [comment]
@bethac07 please rebase

**Comment by AnneCarpenter** [comment]
Do you want me to make a new issue to check the codebase for other instances of this situation?

**Pull request merged**
