### PR TITLE
Overlay labels on image in segmentation display

### LINKED ISSUE #2380: display segmentations in color

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #2380 

Not a great segmentation, but this gives an idea of the output:

screen shot 2016-10-03 at 9 54 14 am

### CODE REVIEW

**Comment by mcquin** [comment]
@bethac07 has spoken!

**Comment by AnneCarpenter** [comment]
Happy to see colored segmentations (or as my littlest recently called them -"oooh!  Jelly beans!")  

A question: is the colormap selectable for the label matrices (in general but also for the 3D case)? I can't recall if our recent discussion related to colormaps for saving grayscale images or if it also applied to label matrices. Just curious.

**Comment by mcquin** [comment]
LOL! @bethac07 thought these looked like Easter eggs. But I like jelly beans, too.

The color map is not selectable for label matrices on display. I have not looked into saving, yet.

**Comment by AnneCarpenter** [comment]
Definitely not a request, I doubt anyone NEEDS it, it's just something that had the potential to bring joy. 😊

**Pull request merged**
