### PR TITLE
[WIP] MergeObjects module merges two objects.

### PR DESCRIPTION
**Pull request by mcquin**
Merge two objects into one object using the MergeObjects module. TODOs:
1. Decide what to do when two distinct objects overlap. One suggestion is to merge them together. Another suggestion is to follow the MaskObjects approachand split the overlapping segments across their intersection.
2. Set object labels and IVJ values. Thankfully, these support overlapping objects. That is, we should be able to give one point multiple labels. We should only do this if a) this is the correct interpretation of this functionality and b) we decide to not join overlapping segments.
3. Decide if there is a more appropriate name for this module. Current suggestions include: UnionObjects, CombineObjects, ______.
4. Other TODOs may be listed in the code. Do them. Also, fix failing tests.

/cc @0x00B1

### CODE REVIEW

**Comment by bethac07** [comment]
Mark and Lee were discussing "MergeIdentifiedObjects" in #876 as a name; I think that using "merge" even with the "Identified" in there might give the wrong impression, perhaps CombineObjectTypes or CombineDifferentObjects ?

**Comment by braymp** [comment]
I think "CombineObjects" would get the point across.

One question, though: Was placing this as an option in ReassignObjectNumbers given consideration? (granted, it's one of the worst named modules ever, but still...)

**Comment by AnneCarpenter** [comment]
My votes:
1. Definitely offer users all possible options for what to do with overlaps because they all make sense for various applications: delete overlapping pixels altogether, include overlapping pixels in both objects, assign overlapping pixels to class A, assign overlapping pixels to class B, merge the two objects and give the resulting object a single label, and (bonus points), split the overlapping pixels evenly (i.e., using Voronoi). 

3. Name: definitely not MergeObjects because it implies objects will be physically merged with nearby neighbors, which will be only one of the options. UnionObjects gets my downvote because users won't typically know that word and it's not a verb; UniteObjects isn't much better for the same reason as Merge. So far CombineObjects seems the best candidate. Maybe even CombineObjectTypes? Adding "Types" may make things a lot clearer whatever name we choose; suddenly MergeObjectTypes doesn't seem so bad. @karhohs and @bethac07 and @braymp should ponder the name thing deeply.

5. Make a new issue offering the user to choose a percentage overlap above which objects are merged and below which they are split (I think it will be relatively common that you want objects to remain separate if they are only overlapping a teeny bit, but merged if they are overlapping a lot).

**Comment by braymp** [comment]
I'm not keen on the "Types" suffix since it's not clear what "type" refers to or means. E.g., MaskObjects and RelateObjects are fine as names, and both can manipulate any objects the user choses.

I like the percentage idea; MaskObjects has the same option. It also need to be made clear in the setting text which object the percentage refers to. Since I'm imagining the settings are arranged much like MaskObjects, there could be two settings:
* Perform operation depending on overlap?: yes/no (using "operation" to keep it generic)
* (Expose if "yes" to above) Fraction of allowed overlap with first object: Float between 0,1 (to be consistent with MaskObjects)

**Comment by AnneCarpenter** [comment]
Another todo, per https://github.com/CellProfiler/CellProfiler/issues/876 

"Add another object" button, in case the user has three or more object types that they want to combine.

I don't know how valuable this is, it's just that Mark requested it.

**Comment by AnneCarpenter** [comment]
FYI, we've settled on renaming ReassignObjectNumbers to be SplitOrMergeObjects in this other issue: https://github.com/CellProfiler/CellProfiler/issues/632  
 
For this new module you're working on, we could do things step-wise: initially, just make this standalone module called whatever you like, maybe CombineObjects. 

But eventually, it would embed into SplitOrMergeObjects. You may wish to go straight to this route right away so we don't need to build any backwards compatibility for a module that will soon be outdated. 

It would keep the current first Q: "Select the input objects" and the next Q would be "Do you want to merge with another object type?" If yes, the current options in SplitOrMergeObjects go away and instead you get the WIP module's options. I think it would be too messy to allow users, in a single module, to combine two different object types AND ALSO merge objects within a certain distance etc. The user can always just run two copies of the SplitOrMergeObjects module if they want to do that.

(Now, note our overall strategy in module complexity in CellProfiler: our user base appreciates being able to scan all the modules and selecting among them. Instead of having a separate module for every little function in CellProfiler, we prefer to have modules with fairly broad functionality so the user isn't overwhelmed with tons of options. We have ~15 object modules and ~25 image processing modules currently. We can argue about exactly where the line is drawn, though, so it's up for debate whether the WIP module should be a separate one. To me it seems to confusing to have a module called SplitOrMergeObjects and a separate one called CombineObjects, hence my recommendation to combine the functionality in a single module, SplitOrMergeObjects.)

**Comment by 0x00B1** [comment]
@AnneCarpenter and @braymp Has a module been renamed in the past? I don’t understand how this would work without breaking backwards-compatability outside of retaining both names inside of CellProfiler since CellProfiler identifies modules by a string value (e.g. “crop”) rather than a unique and immutable identifier (e.g. a random integer).

**Comment by AnneCarpenter** [comment]
Indeed, we renamed modules a lot, and Lee patiently backwards compatibilized them for us. But I don't know how.

**Comment by 0x00B1** [comment]
> Indeed, we renamed modules a lot, and Lee patiently backwards compatibilized them for us. But I don't know how.

I just looked. He kept both identifiers. This is annoying. We should stop using names (i.e. strings) for keys.

**Comment by AnneCarpenter** [comment]
Fine by me  :D

**Comment by 0x00B1** [comment]
I don’t think this should include the “by percentage” feature. It’s too annoying to implement when nobody has an immediate use.

> (Now, note our overall strategy in module complexity in CellProfiler: our user base appreciates being able to scan all the modules and selecting among them. Instead of having a separate module for every little function in CellProfiler, we prefer to have modules with fairly broad functionality so the user isn't overwhelmed with tons of options. We have ~15 object modules and ~25 image processing modules currently. We can argue about exactly where the line is drawn, though, so it's up for debate whether the WIP module should be a separate one. To me it seems to confusing to have a module called SplitOrMergeObjects and a separate one called CombineObjects, hence my recommendation to combine the functionality in a single module, SplitOrMergeObjects.)

I disagree. 😝

**Comment by 0x00B1** [comment]
My proposed name: “Join Segmentation.”

**Comment by AnneCarpenter** [comment]
Personally, I suspect the functionality in the module is nearly useless without the percentage function; else, it will only work for very sparse, nicely spaced objects which are a rarity for us. Others should chime in on that, though.

Yeah, we could devote a whole coding day to debating, as Lee once put it, "unfortunate tension between having a giant jumble of very clean, single-purpose modules and having a small number of nicely categorized modules, each of which is a giant jumble of sometimes loosely-connected functions."

I think both options are sane choices. But we've chosen the latter (largely because users value being able to skim a small number of nicely categorized modules).

**Comment by braymp** [comment]
@0x00B1: Similar case in point re: percentage: I often use MaskObjects over RelateObjects for precisely this reason. RelateObjs will parent an object if there is only pixel of overlap, which is almost always not what you want. 

I can easily imagine an instance where this new module merges two barely touching objects, and that result being the wrong answer.

**Comment by karhohs** [comment]
Merge objects could add additional options to the unify operation of merging objects. In addition to merging based upon distance, there would be the merging based on size. Objects below a size threshold would be merged together until these new objects were above the threshold. There could also be a "gravity" effect, where if a small object is near two larger objects, the larger objects would exert a kind of "pull" to decide which object the smaller object should merge to. The pulling force would be a function of size and distance.

**Comment by mcquin** [comment]
Finishing this is not currently a priority.

**Comment by braymp** [comment]
I'm slightly sad about this. :frowning:

**Comment by mcquin** [comment]
@braymp the issue is still open :)

**Comment by leeleavitt** [comment]
I want this attribute so bad.  Even a simple add objects would be nice.

**Comment by braymp** [comment]
@leeleavitt: Could you use IdentifyTeritiary for what you describe? I believe it works even if the larger/smaller objects are not related via identifySecondary.
And yes, I'd love to see this attribute as well :smile:

**Pull request closed without merging**
