### PR TITLE
Fixed apostrophe in Manders

### PR DESCRIPTION
**Pull request by VRSingan**

### CODE REVIEW

**Comment by 0x00B1** [comment]
:anguished: 

Oops! Thanks!

**Comment by dlogan** [comment]
I would merge this Vasanth ( @VRSingan ) but I think @0x00B1 is going to need to fix the Travis build issue first.

**Comment by VRSingan** [comment]
Sure David. Thanks !

**Comment by 0x00B1** [comment]
@VRSingan please rebase:

```sh

$ git fetch upstream
$ git checkout VRSingan-master 
$ git rebase -i upstream/master
$ git push origin VRSingan-master -f
```

Thanks!

**Comment by VRSingan** [comment]
Hi Allen, I believe the rebase is done. Can you check ?

-Vasanth

**Comment by 0x00B1** [comment]
Merged! Thanks!

**Pull request merged**
