### PR TITLE
Yeast Toolbox

### PR DESCRIPTION
**Pull request by 0x00b1**
previous pull request: #1367.

### CODE REVIEW

**Comment by 0x00B1** [comment]
Because your pull request was nearing 100 commits (!!!), I squashed.

Let’s work from `sstoma-yit` until we merge.

**Comment by 0x00B1** [comment]
- [ ] move `cellprofiler.cpmath.neighmovetrack` into `centrosome`

**Comment by 0x00B1** [comment]
I created a repository for CellStar:

https://github.com/CellProfiler/cellstar

**Comment by 0x00B1** [comment]
I created a pull request for `neighmovetrack` on `centrosome`:

https://github.com/CellProfiler/centrosome/pull/56

**Comment by Fafa87** [comment]
Hi!
I've just restarted working on that pull request.
I have already finished pull requests for the big changes (centrosome, cellstar).

Could you rebase that branch? I will then finish work on my rebased fork.

**Comment by mcquin** [comment]
Hi @Fafa87 you should be able to check out and rebase this branch locally. The pull request was closed but not deleted, and the branch still exists.

**Comment by Fafa87** [comment]
Ok so just to be clear:
1. Rebase branch in my fork.
2. Work on it until it is perfect :)
3. Make a new pull request.

**Comment by mcquin** [comment]
Correct. Please ensure your fork is up to date with our master branch. :)

**Pull request closed without merging**
