### PR TITLE
Changed the CropObjects module to save the cropped object from the original image.

### PR DESCRIPTION
**Pull request by SariNusier**
I believe that issue #2255 is referring to being able to crop the original image for each object. I've made some small changes to the CropObjects module to create an image for each individual object. This crops a rectangle around the object and saves that as an image.

Please let me know if this is something you are looking to implement in the future.

### CODE REVIEW

**Comment by mcquin** [comment]
Hi @SariNusier -

The option to export per-object masks is really import and we need to keep that functionality available. I am not against introducing new options to this module which allows users to export images cropped to bounding boxes.

Also, I suggest using [scikit-image region properties](http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops) to determine bounding boxes.

**Comment by SariNusier** [comment]
Hi @mcquin 

Thanks for the reply. The thing that I wrote wasn't really meant for a PR, it was just a mod I did as a workaround. If you want I can implement it properly, but I wasn't sure whether you guys were planning on doing it as well.  I would be more than happy to implement it.

**Comment by mcquin** [comment]
Yeah! I think it would be great to have this functionality in addition to the per-object masks. It's not high on my current list of priorities; I'd welcome the contribution! :)

**Comment by AnneCarpenter** [comment]
Hi everyone, I'm a little stuck following the issues/comments for this... did anyone end up submitting a PR for anything to add this functionality? AFAICT we just have savecroppedobjects.py which only saves masks, not the original pixel intensity data.

**Comment by SariNusier** [comment]
Hi @AnneCarpenter. I've submitted a PR #2831 which was adding the functionality to also save the cropped image. I think there was a suggestion left which was to add cropping for 3D objects as well. I remember starting to work on that, but noticing someone else adding the feature. Can you please confirm if this is still needed or if someone else has done it already? I am more than happy to submit the change for 2D (and later on follow-up with the change for 3D).

**Comment by AnneCarpenter** [comment]
Thanks!!

I suspect @0x00b1 might be the only one who knows whether someone else added the feature. I'm pretty sure not.

If not, then your 2D version's PR would be super welcome, 2D is probably ~95% of the use cases.

**Pull request closed without merging**
